name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking change'
  - title: 'Featured Changes'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Other Changes'
    labels:
      - 'documentation'

autolabeler:
  - label: 'fix'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
  
change-template: '- $TITLE @$AUTHOR [#$NUMBER]'
template: |
  Homebridge Apt Package Manifest

  | Package | Version |
  |:-------:|:-------:|
  |NodeJS| v*.*.* |
  |Homebridge-Config-UI-X| *.*.* |
  |Homebridge| *.*.* |
  
  ## Other Changes
  $CHANGES

prerelease: true