name: "Stage 3.5 - Purge Cloudflare Cache"

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      CLOUDFLARE_API_TOKEN:
        required: true
      CLOUDFLARE_ZONE_ID:
        required: true

jobs:
  purge_cloudflare_cache:
    name: Purge Cloudflare Cache
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Purge Cloudflare Cache
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
      run: ./purge-cf-cache.sh
